#!/usr/bin/env bash
# =============================================================================
# adapters/copilot-cli/adapter.sh - GitHub Copilot CLI platform adapter
# =============================================================================
# Copilot CLI reads AGENTS.md at the project (or vault) root for machine
# instructions. Skills are discovered from ~/.copilot/skills/<name>/SKILL.md
# and invoked via `/skills <name>` or by description-matching. There is no
# user-level commands/ directory, so each OSB command becomes a standalone
# SKILL.md under .copilot/skills/<slug>/.
#
# SKILL.md frontmatter (agentskills.io spec):
#   name:         kebab-case, ≤64 chars, matches the enclosing folder name
#   description:  what this skill does and when to invoke it (10-1024 chars)
#   license:      MIT  (optional but informative)
#   allowed-tools: execute  (optional; lets the skill run shell commands)
# =============================================================================

COPILOT_PLATFORM="copilot-cli"
COPILOT_DIR="copilot"
COPILOT_SKILLS_SUBDIR=".${COPILOT_DIR}/skills"
COPILOT_DISPATCHER="AGENTS.md"

adapter_build() {
  local src="$1" dst="$2"

  _copilot_emit_dispatcher   "$src"           "$dst"
  _copilot_emit_skills       "$src/commands"  "$dst/$COPILOT_SKILLS_SUBDIR"
  _copilot_copy_references   "$src/references" "$dst/.${COPILOT_DIR}/references"
  _copilot_copy_scripts      "$src/scripts"    "$dst/.${COPILOT_DIR}/scripts"
  _copilot_copy_pyproject    "$src"            "$dst"
  _copilot_emit_install_hint "$dst"
}

# ---------------------------------------------------------------------------
# Dispatcher: AGENTS.md - Copilot reads this natively as machine instructions.
# ---------------------------------------------------------------------------
_copilot_emit_dispatcher() {
  local src="$1" dst="$2"
  local out="$dst/$COPILOT_DISPATCHER"

  {
    cat <<'EOF'
# Obsidian Second Brain - Copilot CLI Operating Manual

This vault runs the **obsidian-second-brain** skill. Each command is
packaged as a *skill*: a SKILL.md under `.copilot/skills/<name>/` that
you (the Copilot agent) follow when the user's request matches its trigger.

## How to operate

1. Read `_CLAUDE.md` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily-note format, naming style).
2. When the user's request matches a trigger in the tables below, invoke
   the matching skill (`/skills <name>`) and follow its instructions step
   by step.
3. Treat the AI-first vault rule (`.copilot/references/ai-first-rules.md`)
   as non-negotiable for every note you write: `## For future Claude`
   preamble, rich frontmatter (`type`, `date`, `tags`, `ai-first: true`),
   `[[wikilinks]]` for every person/project/concept, recency markers per
   external claim, sources verbatim, confidence levels where applicable.
4. Do not invent skills. If no skill matches, ask the user what they want
   or fall back to plain natural-language help.

## Skill routing tables (grouped by category)
EOF

    _copilot_emit_routing_table_grouped "$src/commands" "$COPILOT_PLATFORM"
    emit_trigger_reference               "$src/commands" "$COPILOT_PLATFORM"

    cat <<'EOF'

## Trigger conventions

Each skill has trigger phrases listed in its SKILL.md body. Treat those
triggers as primary; the form `/skills <name>` is also always accepted.

## Scripts

Python helpers live under `.copilot/scripts/`. They run via
`uv run -m scripts.research.<name>` from the vault root (or wherever the
skill is installed). The skills that need them document the exact
invocation inside the skill body.

---

*Generated by adapters/copilot-cli/adapter.sh - do not edit manually.*
EOF
  } > "$out"
}

# Custom routing-table emitter using skills-appropriate column headers and
# invocation syntax. Mirrors emit_routing_table_grouped from adapters/lib.sh
# but replaces the "Read this file" column with "How to invoke".
_copilot_emit_routing_table_grouped() {
  local src_dir="$1" platform="$2"
  [[ -d "$src_dir" ]] || return 0

  local tmp_index; tmp_index="$(mktemp)"
  local f name desc cat
  for f in "$src_dir"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$platform" || continue
    name="$(basename "$f" .md)"
    desc="$(parse_frontmatter "$f" description)"
    desc="${desc#\"}"; desc="${desc%\"}"
    desc="${desc#\'}"; desc="${desc%\'}"
    # Clamp description to 120 chars for the routing table cell
    if [[ ${#desc} -gt 120 ]]; then
      desc="${desc:0:117}..."
    fi
    cat="$(parse_frontmatter "$f" category)"
    [[ -z "$cat" ]] && cat="other"
    printf '%s\t%s\t%s\n' "$cat" "$name" "$desc" >> "$tmp_index"
  done

  local all_cats; all_cats="$(awk -F '\t' '{print $1}' "$tmp_index" | sort -u)"

  local emitted=""
  local c
  for c in $CATEGORY_ORDER; do
    if echo "$all_cats" | grep -qx "$c"; then
      _copilot_emit_one_category_section "$c" "$tmp_index"
      emitted+=" $c"
    fi
  done

  # Unknown categories alphabetically
  for c in $all_cats; do
    case " $emitted " in *" $c "*) continue ;; esac
    _copilot_emit_one_category_section "$c" "$tmp_index"
  done

  rm -f "$tmp_index"
}

_copilot_emit_one_category_section() {
  local cat="$1" index_file="$2"
  local title; title="$(_category_title "$cat")"
  printf '\n### %s\n\n' "$title"
  printf '| Skill | What it does | How to invoke |\n'
  printf '|---|---|---|\n'
  awk -F '\t' -v c="$cat" '$1 == c { print $2 "\t" $3 }' "$index_file" \
    | sort \
    | while IFS=$'\t' read -r name desc; do
        printf '| `/%s` | %s | `/skills %s` |\n' "$name" "$desc" "$name"
      done
}

# ---------------------------------------------------------------------------
# Skills emission: each command → .copilot/skills/<slug>/SKILL.md
# ---------------------------------------------------------------------------
_copilot_emit_skills() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0

  local f slug skill_dir skill_file desc desc_len
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$COPILOT_PLATFORM" || continue

    slug="$(basename "$f" .md)"
    skill_dir="$dst/$slug"
    skill_file="$skill_dir/SKILL.md"
    mkdir -p "$skill_dir"

    desc="$(parse_frontmatter "$f" description)"
    # Strip surrounding quotes that some YAML parsers retain
    desc="${desc#\"}"; desc="${desc%\"}"
    desc="${desc#\'}"; desc="${desc%\'}"
    # Clamp to 1024 chars (agentskills.io spec maximum)
    desc_len="${#desc}"
    if [[ $desc_len -gt 1024 ]]; then
      desc="${desc:0:1021}..."
    fi
    # Ensure minimum 10 chars
    if [[ ${#desc} -lt 10 ]]; then
      desc="Run the ${slug} vault operation."
    fi

    {
      printf -- '---\n'
      printf 'name: %s\n' "$slug"
      printf 'description: >-\n'
      # Indent the description under the YAML block scalar key
      printf '  %s\n' "$desc"
      printf 'license: MIT\n'
      printf 'allowed-tools: execute\n'
      printf -- '---\n'
      printf '\n'
      command_body "$f" \
        | { tmp="$(cat)"; echo "$tmp"; } \
        | sed 's/Execute `\/\([^`]*\)`/Use the skill: \/skills \1/g'
    } > "$skill_file"

    # Rewrite tool references and path tokens
    rewrite_tool_neutral "$skill_file"
    rewrite_platform_paths "$skill_file" "$COPILOT_DIR"
  done
}

# ---------------------------------------------------------------------------
# References, scripts, pyproject
# ---------------------------------------------------------------------------
_copilot_copy_references() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
  find "$dst" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    rewrite_platform_paths "$f" "$COPILOT_DIR"
  done
}

_copilot_copy_scripts() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
}

_copilot_copy_pyproject() {
  local src="$1" dst="$2"
  [[ -f "$src/pyproject.toml" ]] && cp "$src/pyproject.toml" "$dst/pyproject.toml"
  [[ -f "$src/uv.lock" ]]        && cp "$src/uv.lock"        "$dst/uv.lock"
}

# ---------------------------------------------------------------------------
# Install hint
# ---------------------------------------------------------------------------
_copilot_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on Copilot CLI

```bash
# From the repo root, after running `bash scripts/build.sh --platform copilot-cli`:

# 1. Install each skill into Copilot's user-level skills directory:
mkdir -p ~/.copilot/skills
cp -R dist/copilot-cli/.copilot/skills/. ~/.copilot/skills/

# 2. Copy AGENTS.md into your vault root (Copilot reads it as machine instructions):
cp dist/copilot-cli/AGENTS.md /path/to/your/vault/AGENTS.md

# 3. Copy references and scripts into your vault's .copilot/ directory:
mkdir -p /path/to/your/vault/.copilot
cp -R dist/copilot-cli/.copilot/references /path/to/your/vault/.copilot/
cp -R dist/copilot-cli/.copilot/scripts    /path/to/your/vault/.copilot/
cp    dist/copilot-cli/pyproject.toml      /path/to/your/vault/
```

After installation, skills are available as `/skills <name>` in Copilot CLI,
or Copilot will infer the right skill from description-matching.

Start Copilot CLI from the vault root so AGENTS.md is in scope.
EOF
}
